"""Add teaching module tables

Revision ID: 4853451568ab
Revises: b09e88ad6828
Create Date: 2026-03-08 01:53:44.648588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4853451568ab'
down_revision = 'b09e88ad6828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capability_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('prerequisite_module_ids', sa.String(), nullable=True),
    sa.Column('completion_type', sa.String(), nullable=True),
    sa.Column('completion_count', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty_tier', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capability_name'], ['capabilities.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('exercise_template_id', sa.String(), nullable=False),
    sa.Column('config_json', sa.String(), nullable=True),
    sa.Column('mastery_json', sa.String(), nullable=True),
    sa.Column('feedback_json', sa.String(), nullable=True),
    sa.Column('hints_json', sa.String(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('unlock_condition', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['teaching_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_module_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['teaching_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_module_progress_user_module', 'user_module_progress', ['user_id', 'module_id'], unique=True)
    op.create_index('ix_user_module_progress_user_status', 'user_module_progress', ['user_id', 'status'], unique=False)
    op.create_table('lesson_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('timing_error_ms', sa.Integer(), nullable=True),
    sa.Column('duration_error_ms', sa.Integer(), nullable=True),
    sa.Column('expected_answer', sa.String(), nullable=True),
    sa.Column('given_answer', sa.String(), nullable=True),
    sa.Column('exercise_params_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lesson_attempts_created', 'lesson_attempts', ['created_at'], unique=False)
    op.create_index('ix_lesson_attempts_user_lesson', 'lesson_attempts', ['user_id', 'lesson_id'], unique=False)
    op.create_table('user_lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('best_streak', sa.Integer(), nullable=True),
    sa.Column('best_accuracy', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_lesson_progress_user_lesson', 'user_lesson_progress', ['user_id', 'lesson_id'], unique=True)
    op.create_index('ix_user_lesson_progress_user_status', 'user_lesson_progress', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_lesson_progress_user_status', table_name='user_lesson_progress')
    op.drop_index('ix_user_lesson_progress_user_lesson', table_name='user_lesson_progress')
    op.drop_table('user_lesson_progress')
    op.drop_index('ix_lesson_attempts_user_lesson', table_name='lesson_attempts')
    op.drop_index('ix_lesson_attempts_created', table_name='lesson_attempts')
    op.drop_table('lesson_attempts')
    op.drop_index('ix_user_module_progress_user_status', table_name='user_module_progress')
    op.drop_index('ix_user_module_progress_user_module', table_name='user_module_progress')
    op.drop_table('user_module_progress')
    op.drop_table('lessons')
    op.drop_table('teaching_modules')
    # ### end Alembic commands ###
